# Generated by Django 5.1 on 2024-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_age_user_name_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
